In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('zimo.txt', header=None)

In [3]:
df

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16
0,0,0x00,0xE0,0x10,0x08,0x08,0x10,0xE0,0x00,0x00,0x0F,0x10,0x20,0x20,0x10,0x0F,0x00
1,1,0x00,0x10,0x10,0xF8,0x00,0x00,0x00,0x00,0x00,0x20,0x20,0x3F,0x20,0x20,0x00,0x00
2,2,0x00,0x70,0x08,0x08,0x08,0x88,0x70,0x00,0x00,0x30,0x28,0x24,0x22,0x21,0x30,0x00
3,3,0x00,0x30,0x08,0x88,0x88,0x48,0x30,0x00,0x00,0x18,0x20,0x20,0x20,0x11,0x0E,0x00
4,4,0x00,0x00,0xC0,0x20,0x10,0xF8,0x00,0x00,0x00,0x07,0x04,0x24,0x24,0x3F,0x24,0x00
5,5,0x00,0x00,0xC0,0x20,0x10,0xF8,0x00,0x00,0x00,0x07,0x04,0x24,0x24,0x3F,0x24,0x00
6,6,0x00,0xE0,0x10,0x88,0x88,0x18,0x00,0x00,0x00,0x0F,0x11,0x20,0x20,0x11,0x0E,0x00
7,7,0x00,0x38,0x08,0x08,0xC8,0x38,0x08,0x00,0x00,0x00,0x00,0x3F,0x00,0x00,0x00,0x00
8,8,0x00,0x70,0x88,0x08,0x08,0x88,0x70,0x00,0x00,0x1C,0x22,0x21,0x21,0x22,0x1C,0x00
9,9,0x00,0xE0,0x10,0x08,0x08,0x10,0xE0,0x00,0x00,0x00,0x31,0x22,0x22,0x11,0x0F,0x00
10,A,0x00,0x00,0xC0,0x38,0xE0,0x00,0x00,0x00,0x20,0x3C,0x23,0x02,0x02,0x27,0x38,0x20
11,B,0x08,0xF8,0x88,0x88,0x88,0x70,0x00,0x00,0x20,0x3F,0x20,0x20,0x20,0x11,0x0E,0x00
12,C,0xC0,0x30,0x08,0x08,0x08,0x08,0x38,0x00,0x07,0x18,0x20,0x20,0x20,0x10,0x08,0x00
13,D,0x08,0xF8,0x08,0x08,0x08,0x10,0xE0,0x00,0x20,0x3F,0x20,0x20,0x20,0x10,0x0F,0x00
14,E,0x08,0xF8,0x88,0x88,0xE8,0x08,0x10,0x00,0x20,0x3F,0x20,0x20,0x23,0x20,0x18,0x00
15,F,0x08,0xF8,0x88,0x88,0xE8,0x08,0x10,0x00,0x20,0x3F,0x20,0x00,0x03,0x00,0x00,0x00

In [4]:
new_df = df.copy()

In [5]:
for i in range(16):
    for j in range(1,17):
        new_df.iloc[i,j] = '{:08b}'.format(int(df.iloc[i,j],16))

In [6]:
new_df

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16
0,0,00000000,11100000,00010000,00001000,00001000,00010000,11100000,00000000,00000000,00001111,00010000,00100000,00100000,00010000,00001111,00000000
1,1,00000000,00010000,00010000,11111000,00000000,00000000,00000000,00000000,00000000,00100000,00100000,00111111,00100000,00100000,00000000,00000000
2,2,00000000,01110000,00001000,00001000,00001000,10001000,01110000,00000000,00000000,00110000,00101000,00100100,00100010,00100001,00110000,00000000
3,3,00000000,00110000,00001000,10001000,10001000,01001000,00110000,00000000,00000000,00011000,00100000,00100000,00100000,00010001,00001110,00000000
4,4,00000000,00000000,11000000,00100000,00010000,11111000,00000000,00000000,00000000,00000111,00000100,00100100,00100100,00111111,00100100,00000000
5,5,00000000,00000000,11000000,00100000,00010000,11111000,00000000,00000000,00000000,00000111,00000100,00100100,00100100,00111111,00100100,00000000
6,6,00000000,11100000,00010000,10001000,10001000,00011000,00000000,00000000,00000000,00001111,00010001,00100000,00100000,00010001,00001110,00000000
7,7,00000000,00111000,00001000,00001000,11001000,00111000,00001000,00000000,00000000,00000000,00000000,00111111,00000000,00000000,00000000,00000000
8,8,00000000,01110000,10001000,00001000,00001000,10001000,01110000,00000000,00000000,00011100,00100010,00100001,00100001,00100010,00011100,00000000
9,9,00000000,11100000,00010000,00001000,00001000,00010000,11100000,00000000,00000000,00000000,00110001,00100010,00100010,00010001,00001111,00000000
10,A,00000000,00000000,11000000,00111000,11100000,00000000,00000000,00000000,00100000,00111100,00100011,00000010,00000010,00100111,00111000,00100000
11,B,00001000,11111000,10001000,10001000,10001000,01110000,00000000,00000000,00100000,00111111,00100000,00100000,00100000,00010001,00001110,00000000
12,C,11000000,00110000,00001000,00001000,00001000,00001000,00111000,00000000,00000111,00011000,00100000,00100000,00100000,00010000,00001000,00000000
13,D,00001000,11111000,00001000,00001000,00001000,00010000,11100000,00000000,00100000,00111111,00100000,00100000,00100000,00010000,00001111,00000000
14,E,00001000,11111000,10001000,10001000,11101000,00001000,00010000,00000000,00100000,00111111,00100000,00100000,00100011,00100000,00011000,00000000
15,F,00001000,11111000,10001000,10001000,11101000,00001000,00010000,00000000,00100000,00111111,00100000,00000000,00000011,00000000,00000000,00000000

In [7]:
for i in range(16):
    for j in range(1,17):
        new_df.iloc[i,j] = ''.join(reversed(new_df.iloc[i,j]))

In [8]:
new_df

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16
0,0,00000000,00000111,00001000,00010000,00010000,00001000,00000111,00000000,00000000,11110000,00001000,00000100,00000100,00001000,11110000,00000000
1,1,00000000,00001000,00001000,00011111,00000000,00000000,00000000,00000000,00000000,00000100,00000100,11111100,00000100,00000100,00000000,00000000
2,2,00000000,00001110,00010000,00010000,00010000,00010001,00001110,00000000,00000000,00001100,00010100,00100100,01000100,10000100,00001100,00000000
3,3,00000000,00001100,00010000,00010001,00010001,00010010,00001100,00000000,00000000,00011000,00000100,00000100,00000100,10001000,01110000,00000000
4,4,00000000,00000000,00000011,00000100,00001000,00011111,00000000,00000000,00000000,11100000,00100000,00100100,00100100,11111100,00100100,00000000
5,5,00000000,00000000,00000011,00000100,00001000,00011111,00000000,00000000,00000000,11100000,00100000,00100100,00100100,11111100,00100100,00000000
6,6,00000000,00000111,00001000,00010001,00010001,00011000,00000000,00000000,00000000,11110000,10001000,00000100,00000100,10001000,01110000,00000000
7,7,00000000,00011100,00010000,00010000,00010011,00011100,00010000,00000000,00000000,00000000,00000000,11111100,00000000,00000000,00000000,00000000
8,8,00000000,00001110,00010001,00010000,00010000,00010001,00001110,00000000,00000000,00111000,01000100,10000100,10000100,01000100,00111000,00000000
9,9,00000000,00000111,00001000,00010000,00010000,00001000,00000111,00000000,00000000,00000000,10001100,01000100,01000100,10001000,11110000,00000000
10,A,00000000,00000000,00000011,00011100,00000111,00000000,00000000,00000000,00000100,00111100,11000100,01000000,01000000,11100100,00011100,00000100
11,B,00010000,00011111,00010001,00010001,00010001,00001110,00000000,00000000,00000100,11111100,00000100,00000100,00000100,10001000,01110000,00000000
12,C,00000011,00001100,00010000,00010000,00010000,00010000,00011100,00000000,11100000,00011000,00000100,00000100,00000100,00001000,00010000,00000000
13,D,00010000,00011111,00010000,00010000,00010000,00001000,00000111,00000000,00000100,11111100,00000100,00000100,00000100,00001000,11110000,00000000
14,E,00010000,00011111,00010001,00010001,00010111,00010000,00001000,00000000,00000100,11111100,00000100,00000100,11000100,00000100,00011000,00000000
15,F,00010000,00011111,00010001,00010001,00010111,00010000,00001000,00000000,00000100,11111100,00000100,00000000,11000000,00000000,00000000,00000000

In [9]:
for i in range(16):
    for j in range(1,17):
        new_df.iloc[i,j] = hex(int(new_df.iloc[i,j],2))

In [10]:
new_df

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16
0,0,0x0,0x7,0x8,0x10,0x10,0x8,0x7,0x0,0x0,0xf0,0x8,0x4,0x4,0x8,0xf0,0x0
1,1,0x0,0x8,0x8,0x1f,0x0,0x0,0x0,0x0,0x0,0x4,0x4,0xfc,0x4,0x4,0x0,0x0
2,2,0x0,0xe,0x10,0x10,0x10,0x11,0xe,0x0,0x0,0xc,0x14,0x24,0x44,0x84,0xc,0x0
3,3,0x0,0xc,0x10,0x11,0x11,0x12,0xc,0x0,0x0,0x18,0x4,0x4,0x4,0x88,0x70,0x0
4,4,0x0,0x0,0x3,0x4,0x8,0x1f,0x0,0x0,0x0,0xe0,0x20,0x24,0x24,0xfc,0x24,0x0
5,5,0x0,0x0,0x3,0x4,0x8,0x1f,0x0,0x0,0x0,0xe0,0x20,0x24,0x24,0xfc,0x24,0x0
6,6,0x0,0x7,0x8,0x11,0x11,0x18,0x0,0x0,0x0,0xf0,0x88,0x4,0x4,0x88,0x70,0x0
7,7,0x0,0x1c,0x10,0x10,0x13,0x1c,0x10,0x0,0x0,0x0,0x0,0xfc,0x0,0x0,0x0,0x0
8,8,0x0,0xe,0x11,0x10,0x10,0x11,0xe,0x0,0x0,0x38,0x44,0x84,0x84,0x44,0x38,0x0
9,9,0x0,0x7,0x8,0x10,0x10,0x8,0x7,0x0,0x0,0x0,0x8c,0x44,0x44,0x88,0xf0,0x0
10,A,0x0,0x0,0x3,0x1c,0x7,0x0,0x0,0x0,0x4,0x3c,0xc4,0x40,0x40,0xe4,0x1c,0x4
11,B,0x10,0x1f,0x11,0x11,0x11,0xe,0x0,0x0,0x4,0xfc,0x4,0x4,0x4,0x88,0x70,0x0
12,C,0x3,0xc,0x10,0x10,0x10,0x10,0x1c,0x0,0xe0,0x18,0x4,0x4,0x4,0x8,0x10,0x0
13,D,0x10,0x1f,0x10,0x10,0x10,0x8,0x7,0x0,0x4,0xfc,0x4,0x4,0x4,0x8,0xf0,0x0
14,E,0x10,0x1f,0x11,0x11,0x17,0x10,0x8,0x0,0x4,0xfc,0x4,0x4,0xc4,0x4,0x18,0x0
15,F,0x10,0x1f,0x11,0x11,0x17,0x10,0x8,0x0,0x4,0xfc,0x4,0x0,0xc0,0x0,0x0,0x0

In [11]:
for i in range(16):
    for j in range(1,17):
        new_df.iloc[i,j] = new_df.iloc[i,j][2:]

In [12]:
new_df

   0   1   2   3   4   5   6   7  8   9   10  11  12  13  14  15 16
0   0   0   7   8  10  10   8   7  0   0  f0   8   4   4   8  f0  0
1   1   0   8   8  1f   0   0   0  0   0   4   4  fc   4   4   0  0
2   2   0   e  10  10  10  11   e  0   0   c  14  24  44  84   c  0
3   3   0   c  10  11  11  12   c  0   0  18   4   4   4  88  70  0
4   4   0   0   3   4   8  1f   0  0   0  e0  20  24  24  fc  24  0
5   5   0   0   3   4   8  1f   0  0   0  e0  20  24  24  fc  24  0
6   6   0   7   8  11  11  18   0  0   0  f0  88   4   4  88  70  0
7   7   0  1c  10  10  13  1c  10  0   0   0   0  fc   0   0   0  0
8   8   0   e  11  10  10  11   e  0   0  38  44  84  84  44  38  0
9   9   0   7   8  10  10   8   7  0   0   0  8c  44  44  88  f0  0
10  A   0   0   3  1c   7   0   0  0   4  3c  c4  40  40  e4  1c  4
11  B  10  1f  11  11  11   e   0  0   4  fc   4   4   4  88  70  0
12  C   3   c  10  10  10  10  1c  0  e0  18   4   4   4   8  10  0
13  D  10  1f  10  10  10   8   7  0   4  fc   4   4   4   8  f0  0
14  E  10  1f  11  11  17  10   8  0   4  fc   4   4  c4   4  18  0
15  F  10  1f  11  11  17  10   8  0   4  fc   4   0  c0   0   0  0

In [13]:
for i in range(16):
    for j in range(1,17):
        new_df.iloc[i,j] = '{:0>2}'.format(new_df.iloc[i,j])

In [14]:
new_df

   0   1   2   3   4   5   6   7   8   9   10  11  12  13  14  15  16
0   0  00  07  08  10  10  08  07  00  00  f0  08  04  04  08  f0  00
1   1  00  08  08  1f  00  00  00  00  00  04  04  fc  04  04  00  00
2   2  00  0e  10  10  10  11  0e  00  00  0c  14  24  44  84  0c  00
3   3  00  0c  10  11  11  12  0c  00  00  18  04  04  04  88  70  00
4   4  00  00  03  04  08  1f  00  00  00  e0  20  24  24  fc  24  00
5   5  00  00  03  04  08  1f  00  00  00  e0  20  24  24  fc  24  00
6   6  00  07  08  11  11  18  00  00  00  f0  88  04  04  88  70  00
7   7  00  1c  10  10  13  1c  10  00  00  00  00  fc  00  00  00  00
8   8  00  0e  11  10  10  11  0e  00  00  38  44  84  84  44  38  00
9   9  00  07  08  10  10  08  07  00  00  00  8c  44  44  88  f0  00
10  A  00  00  03  1c  07  00  00  00  04  3c  c4  40  40  e4  1c  04
11  B  10  1f  11  11  11  0e  00  00  04  fc  04  04  04  88  70  00
12  C  03  0c  10  10  10  10  1c  00  e0  18  04  04  04  08  10  00
13  D  10  1f  10  10  10  08  07  00  04  fc  04  04  04  08  f0  00
14  E  10  1f  11  11  17  10  08  00  04  fc  04  04  c4  04  18  00
15  F  10  1f  11  11  17  10  08  00  04  fc  04  00  c0  00  00  00

In [15]:
for i in range(16):
    for j in range(1,17):
        new_df.iloc[i,j] = new_df.iloc[i,j].upper()

In [16]:
new_df

   0   1   2   3   4   5   6   7   8   9   10  11  12  13  14  15  16
0   0  00  07  08  10  10  08  07  00  00  F0  08  04  04  08  F0  00
1   1  00  08  08  1F  00  00  00  00  00  04  04  FC  04  04  00  00
2   2  00  0E  10  10  10  11  0E  00  00  0C  14  24  44  84  0C  00
3   3  00  0C  10  11  11  12  0C  00  00  18  04  04  04  88  70  00
4   4  00  00  03  04  08  1F  00  00  00  E0  20  24  24  FC  24  00
5   5  00  00  03  04  08  1F  00  00  00  E0  20  24  24  FC  24  00
6   6  00  07  08  11  11  18  00  00  00  F0  88  04  04  88  70  00
7   7  00  1C  10  10  13  1C  10  00  00  00  00  FC  00  00  00  00
8   8  00  0E  11  10  10  11  0E  00  00  38  44  84  84  44  38  00
9   9  00  07  08  10  10  08  07  00  00  00  8C  44  44  88  F0  00
10  A  00  00  03  1C  07  00  00  00  04  3C  C4  40  40  E4  1C  04
11  B  10  1F  11  11  11  0E  00  00  04  FC  04  04  04  88  70  00
12  C  03  0C  10  10  10  10  1C  00  E0  18  04  04  04  08  10  00
13  D  10  1F  10  10  10  08  07  00  04  FC  04  04  04  08  F0  00
14  E  10  1F  11  11  17  10  08  00  04  FC  04  04  C4  04  18  00
15  F  10  1F  11  11  17  10  08  00  04  FC  04  00  C0  00  00  00

In [17]:
for i in range(16):
    for j in range(1,17):
        new_df.iloc[i,j] = new_df.iloc[i,j]+'H'

In [18]:
new_df

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16
0,0,00H,07H,08H,10H,10H,08H,07H,00H,00H,F0H,08H,04H,04H,08H,F0H,00H
1,1,00H,08H,08H,1FH,00H,00H,00H,00H,00H,04H,04H,FCH,04H,04H,00H,00H
2,2,00H,0EH,10H,10H,10H,11H,0EH,00H,00H,0CH,14H,24H,44H,84H,0CH,00H
3,3,00H,0CH,10H,11H,11H,12H,0CH,00H,00H,18H,04H,04H,04H,88H,70H,00H
4,4,00H,00H,03H,04H,08H,1FH,00H,00H,00H,E0H,20H,24H,24H,FCH,24H,00H
5,5,00H,00H,03H,04H,08H,1FH,00H,00H,00H,E0H,20H,24H,24H,FCH,24H,00H
6,6,00H,07H,08H,11H,11H,18H,00H,00H,00H,F0H,88H,04H,04H,88H,70H,00H
7,7,00H,1CH,10H,10H,13H,1CH,10H,00H,00H,00H,00H,FCH,00H,00H,00H,00H
8,8,00H,0EH,11H,10H,10H,11H,0EH,00H,00H,38H,44H,84H,84H,44H,38H,00H
9,9,00H,07H,08H,10H,10H,08H,07H,00H,00H,00H,8CH,44H,44H,88H,F0H,00H
10,A,00H,00H,03H,1CH,07H,00H,00H,00H,04H,3CH,C4H,40H,40H,E4H,1CH,04H
11,B,10H,1FH,11H,11H,11H,0EH,00H,00H,04H,FCH,04H,04H,04H,88H,70H,00H
12,C,03H,0CH,10H,10H,10H,10H,1CH,00H,E0H,18H,04H,04H,04H,08H,10H,00H
13,D,10H,1FH,10H,10H,10H,08H,07H,00H,04H,FCH,04H,04H,04H,08H,F0H,00H
14,E,10H,1FH,11H,11H,17H,10H,08H,00H,04H,FCH,04H,04H,C4H,04H,18H,00H
15,F,10H,1FH,11H,11H,17H,10H,08H,00H,04H,FCH,04H,00H,C0H,00H,00H,00H

In [28]:
new_df.iloc[:,0] = 'DB '+ new_df.iloc[:,1]

In [32]:
new_df

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16
0,DB 00H,00H,07H,08H,10H,10H,08H,07H,00H,00H,F0H,08H,04H,04H,08H,F0H,00H
1,DB 00H,00H,08H,08H,1FH,00H,00H,00H,00H,00H,04H,04H,FCH,04H,04H,00H,00H
2,DB 00H,00H,0EH,10H,10H,10H,11H,0EH,00H,00H,0CH,14H,24H,44H,84H,0CH,00H
3,DB 00H,00H,0CH,10H,11H,11H,12H,0CH,00H,00H,18H,04H,04H,04H,88H,70H,00H
4,DB 00H,00H,00H,03H,04H,08H,1FH,00H,00H,00H,E0H,20H,24H,24H,FCH,24H,00H
5,DB 00H,00H,00H,03H,04H,08H,1FH,00H,00H,00H,E0H,20H,24H,24H,FCH,24H,00H
6,DB 00H,00H,07H,08H,11H,11H,18H,00H,00H,00H,F0H,88H,04H,04H,88H,70H,00H
7,DB 00H,00H,1CH,10H,10H,13H,1CH,10H,00H,00H,00H,00H,FCH,00H,00H,00H,00H
8,DB 00H,00H,0EH,11H,10H,10H,11H,0EH,00H,00H,38H,44H,84H,84H,44H,38H,00H
9,DB 00H,00H,07H,08H,10H,10H,08H,07H,00H,00H,00H,8CH,44H,44H,88H,F0H,00H
10,DB 00H,00H,00H,03H,1CH,07H,00H,00H,00H,04H,3CH,C4H,40H,40H,E4H,1CH,04H
11,DB 10H,10H,1FH,11H,11H,11H,0EH,00H,00H,04H,FCH,04H,04H,04H,88H,70H,00H
12,DB 03H,03H,0CH,10H,10H,10H,10H,1CH,00H,E0H,18H,04H,04H,04H,08H,10H,00H
13,DB 10H,10H,1FH,10H,10H,10H,08H,07H,00H,04H,FCH,04H,04H,04H,08H,F0H,00H
14,DB 10H,10H,1FH,11H,11H,17H,10H,08H,00H,04H,FCH,04H,04H,C4H,04H,18H,00H
15,DB 10H,10H,1FH,11H,11H,17H,10H,08H,00H,04H,FCH,04H,00H,C0H,00H,00H,00H

In [33]:
new_df.drop(columns=1, inplace=True)

In [34]:
new_df

,0,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16
0,DB 00H,07H,08H,10H,10H,08H,07H,00H,00H,F0H,08H,04H,04H,08H,F0H,00H
1,DB 00H,08H,08H,1FH,00H,00H,00H,00H,00H,04H,04H,FCH,04H,04H,00H,00H
2,DB 00H,0EH,10H,10H,10H,11H,0EH,00H,00H,0CH,14H,24H,44H,84H,0CH,00H
3,DB 00H,0CH,10H,11H,11H,12H,0CH,00H,00H,18H,04H,04H,04H,88H,70H,00H
4,DB 00H,00H,03H,04H,08H,1FH,00H,00H,00H,E0H,20H,24H,24H,FCH,24H,00H
5,DB 00H,00H,03H,04H,08H,1FH,00H,00H,00H,E0H,20H,24H,24H,FCH,24H,00H
6,DB 00H,07H,08H,11H,11H,18H,00H,00H,00H,F0H,88H,04H,04H,88H,70H,00H
7,DB 00H,1CH,10H,10H,13H,1CH,10H,00H,00H,00H,00H,FCH,00H,00H,00H,00H
8,DB 00H,0EH,11H,10H,10H,11H,0EH,00H,00H,38H,44H,84H,84H,44H,38H,00H
9,DB 00H,07H,08H,10H,10H,08H,07H,00H,00H,00H,8CH,44H,44H,88H,F0H,00H
10,DB 00H,00H,03H,1CH,07H,00H,00H,00H,04H,3CH,C4H,40H,40H,E4H,1CH,04H
11,DB 10H,1FH,11H,11H,11H,0EH,00H,00H,04H,FCH,04H,04H,04H,88H,70H,00H
12,DB 03H,0CH,10H,10H,10H,10H,1CH,00H,E0H,18H,04H,04H,04H,08H,10H,00H
13,DB 10H,1FH,10H,10H,10H,08H,07H,00H,04H,FCH,04H,04H,04H,08H,F0H,00H
14,DB 10H,1FH,11H,11H,17H,10H,08H,00H,04H,FCH,04H,04H,C4H,04H,18H,00H
15,DB 10H,1FH,11H,11H,17H,10H,08H,00H,04H,FCH,04H,00H,C0H,00H,00H,00H

In [35]:
new_df.to_csv('right_zimo.txt', header=False, index=False)